config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :entries
  resources :users
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  extend Enumerize

  belongs_to :user

  enumerize :feeling, in: { angry: 0, sad: 1, confused: 2, happy: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :entries, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :new, :create]

  def index
    @entries = current_user.entries.all
  end

  def show
  end

  def new
    @entry = Entry.new
  end

  def edit
  end

  def create
    @entry = current_user.entries.new(entry_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @entry.save
        flash[:success] = 'Entry was successfully created.'
        format.html { redirect_to @entry }
        format.json { render :show, status: :created, location: @entry }
      else
        flash.now[:error] = 'Sorry, an error has occured'
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @entry.update(entry_params)
        flash[:success] = 'Entry was successfully updated.'
        format.html { redirect_to @entry }
        format.json { render :show, status: :ok, location: @entry }
      else
        flash.now[:error] = 'Sorry, an error has occured'
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @entry.destroy
    respond_to do |format|
      flash[:success] = 'Entry was successfully destroyed.'
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end

  private
    def set_entry
      @entry = Entry.find(params[:id])
    end

    def entry_params
      params.require(:entry).permit(:feeling, :description, :day, :hour)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        flash[:success] = 'User was successfully created.'
        format.html { redirect_to @user }
        format.json { render :show, status: :created, location: @user }
      else
        flash.now[:error] = 'Sorry, an error has occured'
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        flash[:success] = 'User was successfully updated.'
        format.html { redirect_to @user }
        format.json { render :show, status: :ok, location: @user }
      else
        flash.now[:error] = 'Sorry, an error has occured'
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      flash[:success] = 'User was successfully destroyed.'
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entries/_form.html.erb
<%= form_with(model: entry, local: true) do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% entry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :feeling, t(:feeling, scope: 'activerecord.attributes.entries') %>
    <%= form.select :feeling, Entry.feeling.options %>
  </div>

  <div class="field">
    <%= form.label :description, t(:description, scope: 'activerecord.attributes.entries') %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :hour, t(:hour, scope: 'activerecord.attributes.entries') %>
    <%= form.time_field :hour %>
  </div>

  <div class="field">
    <%= form.label :day, t(:day, scope: 'activerecord.attributes.entries') %>
    <%= form.date_field :day %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1 class="title"><%= t(:entry, scope: 'activerecord.models').pluralize %></h1>

  <table class="table">
    <thead>
      <tr class="columnTitle">
        <th><%= t(:feeling, scope: 'activerecord.attributes.entries') %></th>
        <th><%= t(:description, scope: 'activerecord.attributes.entries') %></th>
        <th><%= t(:hour, scope: 'activerecord.attributes.entries') %></th>
        <th><%= t(:day, scope: 'activerecord.attributes.entries') %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @entries.each do |entry|%>
        <tr class="entrie">
          <td class="column"><%= t(entry.feeling, scope: 'activerecord.attributes.entries.feelings') %></td>
          <td class="column"><%= entry.description %></td>
          <td class="column"><%= entry.hour.try(:strftime, "%I:%M %p") || "-" %></td>
          <td class="column"><%= entry.day || "-" %></td>
          <td class="column"><%= link_to t(:show), entry %></td>
          <td class="column"><%= link_to t(:edit), edit_entry_path(entry) %></td>
          <td class="column"><%= link_to t(:delete), entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to t(:how_are_you), new_entry_path, class: "newEntryButton" %>
</div>

app/views/entries/new.html.erb
<h1><%= I18n.t('new_entry') %></h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t(:feeling, scope: 'activerecord.attributes.entries') %>:</strong>
  <%= t(@entry.feeling, scope: 'activerecord.attributes.entries.feelings') %>
</p>

<p>
  <strong><%= t(:description, scope: 'activerecord.attributes.entries') %>:</strong>
  <%= @entry.description %>
</p>

<p>
  <strong><%= t(:hour, scope: 'activerecord.attributes.entries') %>:</strong>
  <%= @entry.hour.strftime("%I:%M %p")%>
</p>
<p>
  <strong><%= t(:day, scope: 'activerecord.attributes.entries') %>:</strong>
  <%= @entry.day %>
</p>

<%= link_to t(:edit), edit_entry_path(@entry) %> |
<%= link_to t(:back), entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carambolo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= name %>'>
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= I18n.t('site.title') %></title>
    <meta name="description" content="<%= I18n.t('site.description') %>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-fork-ribbon-css/0.2.3/gh-fork-ribbon.min.css" />
    <link rel="stylesheet" href="/assets/main.css">
  </head>

  <body>
    <a class="github-fork-ribbon" href="https://github.com/teresinahc/carambolo" data-ribbon="Fork me on GitHub" title="Fork me on GitHub">Fork me on GitHub</a>
    <div id="particles-js">
      <div class="header">
        <h1>
          <span class="site-title"><%= I18n.t('site.title') %></span>
          <span class="site-description"><%= I18n.t('site.description') %></span>
        </h1>
        <div class="header-icons">
          <a aria-label="Facebook" target="_blank" href="https://www.facebook.com/<%= I18n.t('site.facebook_username') %>"><i class="icon fa fa-facebook" aria-hidden="true"></i></a>
          <a aria-label="Twitter" target="_blank" href="https://twitter.com/<%= I18n.t('site.twitter_username') %>"><i class="icon fa fa-twitter" aria-hidden="true"></i></a>
          <a aria-label="Instagram" target="_blank" href="https://www.instagram.com/<%= I18n.t('site.instagram_username') %>"><i class="icon fa fa-instagram" aria-hidden="true"></i></a>
          <a aria-label="Github" target="_blank" href="https://github.com/<%= I18n.t('site.github_username') %>"><i class="icon fa fa-github-alt" aria-hidden="true"></i></a>
        </div>
        <div class="header-links">
          <a class="link" href="#about" data-scroll><%= I18n.t('site.about') %></a>
          <a class="link" href="#projects" data-scroll><%= I18n.t('site.projects') %></a>
        </div>
      </div>
      <a class="down" href="#about" data-scroll><i class="icon fa fa-chevron-down" aria-hidden="true"></i></a>
    </div>

    <section id="about">
      <div class="user-details">
        <h1><%= I18n.t('site.about') %></h1>
        <h2><%= I18n.t('site.description') %></h2>
      </div>
       <div class="tech">
         <p>
           <%= I18n.t('site.row.first') %>
         </p>
         <p>
           <%= I18n.t('site.row.second') %>
         </p>
         <p>
           <%= I18n.t('site.row.third') %>
         </p>
       </div>
       <center>
         <a class="project-link" href="https://pro.psychcentral.com/psychoeducation/2017/07/cbt-technique-using-the-triple-column-technique-to-change-your-thoughts-to-change-your-life/">
           <%= I18n.t('site.main_article') %>
         </a>
       </center>
    </section><br>

    <hr>

    <section id="projects">
      <div class="user-details">
          <h1 <%= I18n.t('site.app.kind') %></h1>
        </div>
        <div class="user-projects">
          <div class="images-right">
            <img alt="mountains" src="/assets/mountains.jpg" />
          </div>
          <div class="contents">
            <h3><%= I18n.t('site.app.name') %></h3>
            <ul>
              <li><%= I18n.t('site.app.kind') %></li>
            </ul>
            <p><%= I18n.t('site.app.description') %></p>
            <a class="project-link" href="#"><%= I18n.t('site.app.access') %></a>
          </div>
        </div>
      </section>

    <footer class="footer">
      <p>&copy; <%= I18n.t('site.title') %></p>
      <p><a href="https://github.com/teresinahc" target="_blank"><%= I18n.t('site.thc') %></a></p>
    </footer>

    <script src="//cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
    <script src="/assets/sweet-scroll.min.js"></script>
    <script src="/assets/main.js"></script>

  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>